flightbooker/config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root 'flights#flight'
  get 'flights/flight'
  get 'flights/maps'
  get 'flights/login'
  get 'flights/signup'
  get 'flights/searchFlights'
  get 'flights/pickFlight'
  get 'flights/passengerInfo'
  get 'flights/itinerary'
  get 'flights/signup', to: 'users#new'
  post'flights/signup', to: 'users#create'
  get 'flights/login',   to: 'sessions#new'
  post'flights/login',   to: 'sessions#create'
  delete'flights/logout',  to: 'sessions#destroy'
  resources :users
  resources :sessions
end

flightbooker/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

flightbooker/app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

flightbooker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

flightbooker/app/controllers/flights_controller.rb
class FlightsController < ApplicationController


  def signup
    @user = User.new
  end

  def flight
  end

  def maps

  end


  def login
  end


  def searchFlights
  end

  def pickFlight
  end

  def passengerInfo
  end

  def itinerary
  end

  def about
  end
end

flightbooker/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
      # Log the user in and redirect to the user's show page.
    else
      # Create an error message.
      flash[:danger] = 'Invalid email/password combination' # Not quite right!
      #render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end


end

flightbooker/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      log_in @user
      render 'new'
      # Handle a successful save.
    else
      flash[:success] = "Notworking!"
      redirect_to @user
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def signup
    end

    def flight
    end

    def maps

    end


    def login
    end


    def searchFlights
    end

    def pickFlight
    end

    def passengerInfo
    end

    def itinerary
    end

    def about
    end
end

flightbooker/app/helpers/application_helper.rb
module ApplicationHelper
end

flightbooker/app/helpers/flights_helper.rb
module FlightsHelper
end

flightbooker/app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
 def log_in(user)
   session[:user_id] = user.id
 end

 def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
 end

 # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

flightbooker/app/helpers/users_helper.rb
module UsersHelper
end

flightbooker/app/views/flights/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link type="text/js" href="about.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title></title>
  </head>
  <body>
   <div id=wrapper>
    <div id="container" class="grid-container">
      <div id="top" class="grid-item">
        <i id="plane" class="far fa-paper-plane"></i>
        <p id="compname">ZoZo Flights</p>
        <p id="about">About</p>

        <div id="dropdown" class="dropdown">
          <button id="buttoncol" class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </button>
         <div id="menu" class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a id="signin" class="dropdown-item" href="#">Signed in as: <br> Zayneel <i id="astro" class="fas fa-user-astronaut"></i> </a>
          <a id="droplogin"class="dropdown-item" href="#">Login</a>
          <a id="dropsign" class="dropdown-item" href="#">Signup</a>
          <a id="dropsignout" class="dropdown-item" href="#">Signout</a>
         </div>
        </div>
      </div>
      <div id="body" class="grid-item">
        <%= image_tag("cloud.jpg", :alt => "rss feed", :id => 'picture') %>
        <h2 id="about1"> About ZoZo Flights:</h2>
        <p id="para"> I developed this project in order to practice Ruby on Rails framework features. In particular,
        <br> using ActiveRecord as a database layer interacting with the forms on the client-side.
        <br> In addition, to work with Rails login/auth gems. <br>
        <br>This project was built using: Ruby on Rails, JavaScript (jQuery/Bootstrap)<br></p>

      </div>
      <div id="footer" class="grid-item">
        <p id="foottext1"> © 2019 ZoZo Flights, Inc.</p>
        <p id="foottext2"> Find the cheapest and best flight for you!</p>
        <i id="git" class="fab fa-github"></i>
        <i id="linkedin" class="fab fa-linkedin"></i>
        <i id="email" class="far fa-envelope"></i>

      </div>
    </div>
  </div>
  </body>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script type="text/javascript" src="flights_main.js"></script>
</html>

flightbooker/app/views/flights/flight.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link type="text/js" href="flights.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title></title>
  </head>
  <body>
   <div id=wrapper>
    <div id="container" class="grid-container">
      <div id="top" class="grid-item">
        <i id="plane" class="far fa-paper-plane"></i>
        <p id="compname">ZoZo Flights</p>

        <p id="about">About</p>

        <div id="dropdown" class="dropdown">
          <button id="buttoncol" class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </button>
         <div id="menu" class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a id="signin" class="dropdown-item" href="#">Signed in as: <br> Zayneel <i id="astro" class="fas fa-user-astronaut"></i> </a>
          <a id="droplogin"class="dropdown-item" href="#">Login</a>
          <a id="dropsign" class="dropdown-item" href="#">Signup</a>
          <a id="dropsignout" class="dropdown-item" href="#">Signout</a>
         </div>
        </div>
      </div>
      <div id="body" class="grid-item">
        <%= image_tag("cloud.jpg", :alt => "rss feed", :id => 'picture') %>

        <p id="bodytitle">Find. Compare. <br>Fly!</br></p>
        <div id="passenger" class="dropdown">
          <button id="passbtn" class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i></i>
            1 Passenger
          </button>

        </div>

        <div id="seatclass" class="dropdown">
          <button id="seatbtn" class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i></i>
            Economy
          </button>

        </div>

        <div id="from" class="dropdown">
          <button id="frombtn" class="btn btn-secondary" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i id="fromplane" class="fas fa-plane-departure"></i>
            From?
          </button>
          <div id="frommenu" class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a id="sf" class="dropdown-item" href="#">San francisco</a>
            <a id="ny" class="dropdown-item" href="#">New York</a>
            <a id="par" class="dropdown-item" href="#">Paris</a>
          </div>
        </div>

        <i id="exchange" class="fas fa-exchange-alt"></i>

        <div id="to" class="dropdown">
          <button id="tobtn" class="btn btn-secondary" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i id="fromplane" class="fas fa-plane-departure"></i>
            To?
          </button>
          <div id="tomenu" class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a id="sfto" class="dropdown-item" href="#">San francisco</a>
            <a id="nyto" class="dropdown-item" href="#">New York</a>
            <a id="parto"class="dropdown-item" href="#">Paris</a>
          </div>
        </div>

        <div id="depart" class="dropdown">
          <button id="deparbtn" class="btn btn-secondary" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="fas fa-calendar-alt"></i></i>
            Depart
          </button>
          <div id="departmenu" class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a id="ap1"class="dropdown-item" href="#">April 1st</a>
            <a id="ap2"class="dropdown-item" href="#">April 2nd</a>
            <a id="ap3"class="dropdown-item" href="#">April 3rd</a>
          </div>
        </div>

        <a id="search" href="#" class="btn btn-primary"><span class="glyphicon glyphicon-plane"></span> <i id="searchcircle" class="fas fa-search-location"></i></a>

      </div>

      <div id="flightpick" class="list-group">

  <a href="#" id="pick1" class="list-group-item list-group-item-action flex-column align-items-start active">

    <div class="d-flex w-100 justify-content-between">
      <h5 id="city1" class="mb-1">San Francisco</h5>
      <h5 id="city-" class="mb-1"> - </h5>
      <h5 id="city2" class="mb-1">Paris</h5>
      <h5 id="time" class="mb-1">12h 42m</h5>
      <h5 id="date" class="mb-1">April 1st</h5>
      <small id="price1">$780</small>
    </div>
    <p id="airline" class="mb-1">Zanlandia Airlines</p>
  </a>

  <a href="#" id="pick2" class="list-group-item list-group-item-action flex-column align-items-start active">
    <div class="d-flex w-100 justify-content-between">
      <h5 id="city1" class="mb-1">San Francisco</h5>
      <h5 id="city-" class="mb-1"> - </h5>
      <h5 id="city2" class="mb-1">Paris</h5>
      <h5 id="time2" class="mb-1">10h 01m</h5>
      <h5 id="date" class="mb-1">April 1st</h5>
      <small id="price2">$998</small>
    </div>
    <p id="airline" class="mb-1">Shleby Airlines</p>
  </a>
  <a href="#" id="pick3" class="list-group-item list-group-item-action flex-column align-items-start active">
    <div class="d-flex w-100 justify-content-between">
      <h5 id="city1" class="mb-1">San Francisco</h5>
      <h5 id="city-" class="mb-1"> - </h5>
      <h5 id="city2" class="mb-1">Paris</h5>
      <h5 id="time3" class="mb-1">8h 42m</h5>
      <h5 id="date" class="mb-1">April 1st</h5>
      <small id="price3">$1400</small>
    </div>
    <p id="airline" class="mb-1">Zorya Airways</p>
  </a>
</div>

      <div id="footer" class="grid-item">
        <p id="foottext1"> © 2019 ZoZo Flights, Inc.</p>
        <p id="foottext2"> Find the cheapest and best flight for you!</p>
        <i id="git" class="fab fa-github"></i>
        <i id="linkedin" class="fab fa-linkedin"></i>
        <i id="email" class="far fa-envelope"></i>

      </div>
    </div>
  </div>

</div>
  </body>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script type="text/javascript" src="flights_main.js"></script>
</html>

flightbooker/app/views/flights/itinerary.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link type="text/js" href="itinerary.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title></title>
  </head>
  <body>
   <div id=wrapper>
    <div id="container" class="grid-container">
      <div id="top" class="grid-item">
        <i id="plane" class="far fa-paper-plane"></i>
        <p id="compname">ZoZo Flights</p>

        <p id="about">About</p>

        <div id="dropdown" class="dropdown">
          <button id="buttoncol" class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </button>
         <div id="menu" class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a id="signin" class="dropdown-item" href="#">Signed in as: <br> Zayneel <i id="astro" class="fas fa-user-astronaut"></i> </a>
          <a id="droplogin"class="dropdown-item" href="#">Login</a>
          <a id="dropsign" class="dropdown-item" href="#">Signup</a>
          <a id="dropsignout" class="dropdown-item" href="#">Signout</a>
         </div>
        </div>
      </div>
      <div id="body" class="grid-item">
        <%= image_tag("cloud.jpg", :alt => "rss feed", :id => 'picture') %>


        <div class="jumbotron text-xs-center">
<h1 class="display-3">Thank You for your booking!</h1>
<p class="lead"><strong>Please signup</strong> to save your booking!


</div>



      </div>



      <div id="footer" class="grid-item">
        <p id="foottext1"> © 2019 ZoZo Flights, Inc.</p>
        <p id="foottext2"> Find the cheapest and best flight for you!</p>
        <i id="git" class="fab fa-github"></i>
        <i id="linkedin" class="fab fa-linkedin"></i>
        <i id="email" class="far fa-envelope"></i>

      </div>
    </div>
  </div>
  </body>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script type="text/javascript" src="flights_main.js"></script>
</html>

flightbooker/app/views/flights/login.html.erb
<header>
ZoZo Flights
</header>
<div class="login">
<i ripple>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
<path fill="#C7C7C7" d="m12,2c-5.52,0-10,4.48-10,10s4.48,10,10,10,10-4.48,10-10-4.48-10-10-10zm1,17h-2v-2h2zm2.07-7.75-0.9,0.92c-0.411277,0.329613-0.918558,0.542566-1.20218,1.03749-0.08045,0.14038-0.189078,0.293598-0.187645,0.470854,0.02236,2.76567,0.03004-0.166108,0.07573,1.85002l-1.80787,0.04803-0.04803-1.0764c-0.02822-0.632307-0.377947-1.42259,1.17-2.83l1.24-1.26c0.37-0.36,0.59-0.86,0.59-1.41,0-1.1-0.9-2-2-2s-2,0.9-2,2h-2c0-2.21,1.79-4,4-4s4,1.79,4,4c0,0.88-0.36,1.68-0.930005,2.25z"/>
</svg>
</i>
<div class="photo">
</div>
<span>Sign in to your ZoZo Flights Account</span>

<%= form_for(:session, url: flights_login_path) do |f| %>

<div id="u" class="form-group">
  <input id="session_email" spellcheck=false class="form-control" name="session[email]" type="text" size="18" alt="login" required="">
  <span class="form-highlight"></span>
  <span class="form-bar"></span>
  <label for="username" class="float-label">Email</label>
  <erroru>
  	Email is required
  	<i>
		<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
		    <path d="M0 0h24v24h-24z" fill="none"/>
		    <path d="M1 21h22l-11-19-11 19zm12-3h-2v-2h2v2zm0-4h-2v-4h2v4z"/>
		</svg>
  	</i>
  </erroru>
</div>
<div id="p" class="form-group">
  <input id="session_password" class="form-control" spellcheck=false name="session[password]" type="password" size="18" alt="login" required="">
  <span class="form-highlight"></span>
  <span class="form-bar"></span>
  <label for="password" class="float-label">Password</label>
  <errorp>
  	Password is required
  	<i>
		<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
		    <path d="M0 0h24v24h-24z" fill="none"/>
		    <path d="M1 21h22l-11-19-11 19zm12-3h-2v-2h2v2zm0-4h-2v-4h2v4z"/>
		</svg>
  	</i>
  </errorp>
</div>
<div class="form-group">
<input type="checkbox" id="rem">
<label for="rem">Stay Signed in</label>
<%= f.submit "Sign up !", class: "btn btn-primary" %>
</div>
</form>
<% end %>
<footer><a href="#0"><%= link_to "Create an account!", flights_signup_path %></a></footer>

</div>

flightbooker/app/views/flights/maps.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link type="text/js" href="maps.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title></title>
  </head>
  <body>
   <div id=wrapper>
    <div id="container" class="grid-container">
      <div id="top" class="grid-item">
        <i id="plane" class="far fa-paper-plane"></i>
        <p id="compname">ZoZo Flights</p>

        <p id="about">About</p>

        <div id="dropdown" class="dropdown">
          <button id="buttoncol" class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </button>
         <div id="menu" class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a id="signin" class="dropdown-item" href="#">Signed in as: <br> Zayneel <i id="astro" class="fas fa-user-astronaut"></i> </a>
          <a id="droplogin"class="dropdown-item" href="#">Login</a>
          <a id="dropsign" class="dropdown-item" href="#">Signup</a>
          <a id="dropsignout" class="dropdown-item" href="#">Signout</a>
         </div>
        </div>
      </div>
      <div id="body" class="grid-item">
        <%= image_tag("cloud.jpg", :alt => "rss feed", :id => 'picture') %>

        <div id="user-profile-2" class="user-profile">
		<div class="tabbable">


			<div class="tab-content no-border padding-24">
				<div id="home" class="tab-pane in active">
					<div class="row">
						<div class="col-xs-12 col-sm-3 center">
							<span class="profile-picture">
								<%= image_tag("zozo2.png", :alt => "rss feed", :id => 'avatar2') %>
							</span>

							<div class="space space-4"></div>
						</div><!-- /.col -->

						<div class="col-xs-12 col-sm-9">
							<h4 class="blue">
								<span class="middle">ZoZo Sagar</span>

								<span class="label label-purple arrowed-in-right">
									<i class="ace-icon fa fa-circle smaller-80 align-middle"></i>
									online
								</span>
							</h4>

							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Name: </div>

									<div class="profile-info-value">
										<span> <%= @user.name %></span>
									</div>
								</div>



								<div class="profile-info-row">
									<div class="profile-info-name"> Username: </div>

									<div class="profile-info-value">
										<span>ZoZo</span>
									</div>
								</div>

								<div class="profile-info-row">
									<div class="profile-info-name"> Joined </div>

									<div class="profile-info-value">
										<span>2010/06/20</span>
									</div>
								</div>
							</div>

							<div class="hr hr-8 dotted"></div>

							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Bookings: </div>

                  <div class="profile-info-value">
										<span>Display Bookings</span>
									</div>
								</div>

							</div>
						</div><!-- /.col -->
					</div><!-- /.row -->

					<div class="space-20"></div>

					<div class="row">
						<div class="col-xs-12 col-sm-6">
							<div class="widget-box transparent">
								<div class="widget-header widget-header-small">
									<h4 class="widget-title smaller">
										<i class="ace-icon fa fa-check-square-o bigger-110"></i>
										Bookings:
									</h4>
								</div>

								<div class="widget-body">
									<div class="widget-main">
										<p>
											Flying soon! (put confo box)
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div><!-- /#home -->
  </div>
  </body>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script type="text/javascript" src="flights_main.js"></script>
</html>

flightbooker/app/views/flights/pickFlight.html.erb
<h1>Flights#pickFlight</h1>
<p>Find me in app/views/flights/pickFlight.html.erb</p>

flightbooker/app/views/flights/searchFlights.html.erb
<h1>Flights#searchFlights</h1>
<p>Find me in app/views/flights/searchFlights.html.erb</p>

flightbooker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flightbooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>